"""Extract Dexmate's pre-authored cuRobo-style collision spheres to a cuRobo YAML.

Reads:  third_party/dexmate_urdf/.../vega_1_gripper_collision_spheres.collision.urdf
Writes: src/bio_sim/robot/spheres/dexmate_vega_gripper.yml

Only manipulation-relevant links are emitted (wheels, sensor mounts, IMU, lidar
are skipped — those don't appear in dexmate_planning.urdf and aren't planned
against).
"""

from __future__ import annotations

import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_URDF = REPO_ROOT / "third_party/dexmate_urdf/robots/humanoid/vega_1/vega_1_gripper_collision_spheres.collision.urdf"
DST_YML = REPO_ROOT / "src/bio_sim/robot/spheres/dexmate_vega_gripper.yml"

SKIP_PATTERNS = [
    re.compile(r"^[BLR]_wheel_l[12]$"),
    re.compile(r".*_cam$"),
    re.compile(r".*_cam_mount$"),
    re.compile(r"^imu$"), re.compile(r"^imu_mount$"),
    re.compile(r"^lidar$"), re.compile(r"^lidar_mount$"),
    re.compile(r".*_ultrasonic$"), re.compile(r".*_ultrasonic_mount$"),
    re.compile(r"^zed_.*$"),
    re.compile(r".*_hand_mount$"),
]


def should_skip(link_name: str) -> bool:
    return any(p.match(link_name) for p in SKIP_PATTERNS)


def main() -> int:
    if not SRC_URDF.exists():
        print(f"missing: {SRC_URDF}", file=sys.stderr)
        print("run `python scripts/download_assets.py` first.", file=sys.stderr)
        return 1

    tree = ET.parse(SRC_URDF)
    root = tree.getroot()

    DST_YML.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Auto-generated by scripts/extract_collision_spheres.py — do not edit by hand.\n"]
    total_links = 0
    total_spheres = 0
    for link in root.findall("link"):
        name = link.get("name", "")
        if should_skip(name):
            continue
        spheres = []
        for col in link.findall("collision"):
            sphere = col.find("geometry/sphere")
            if sphere is None:
                continue
            origin = col.find("origin")
            xyz = origin.get("xyz") if origin is not None else "0 0 0"
            cx, cy, cz = (float(v) for v in xyz.split())
            r = float(sphere.get("radius", "0"))
            spheres.append((cx, cy, cz, r))
        if not spheres:
            continue
        lines.append(f"{name}:\n")
        for cx, cy, cz, r in spheres:
            lines.append(f"  - center: [{cx:.6f}, {cy:.6f}, {cz:.6f}]\n")
            lines.append(f"    radius: {r:.6f}\n")
        total_links += 1
        total_spheres += len(spheres)

    DST_YML.write_text("".join(lines))
    print(f"wrote {DST_YML.relative_to(REPO_ROOT)}")
    print(f"  links: {total_links}, total spheres: {total_spheres}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
